package com.example.aa.aaapp.greendao.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * This entity is used for AccountBook.
 * (This JavaDoc is defined in the generator project.)
 */
// This is another test comment, you could also apply annotations like this
public class AccountBookEntity {

    private Long accountBookId;
    /** Not-null value. */
    private String accountBookName;
    /** Not-null value. */
    private String state;
    private int isDefault;
    /** Not-null value. */
    private java.util.Date createDate;

    public AccountBookEntity() {
    }

    public AccountBookEntity(Long accountBookId) {
        this.accountBookId = accountBookId;
    }

    public AccountBookEntity(Long accountBookId, String accountBookName, String state, int isDefault, java.util.Date createDate) {
        this.accountBookId = accountBookId;
        this.accountBookName = accountBookName;
        this.state = state;
        this.isDefault = isDefault;
        this.createDate = createDate;
    }

    public Long getAccountBookId() {
        return accountBookId;
    }

    public void setAccountBookId(Long accountBookId) {
        this.accountBookId = accountBookId;
    }

    /** Not-null value. */
    /**
     * JavaDoc test getter and setter
     */
    public String getAccountBookName() {
        return accountBookName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    /**
     * JavaDoc test getter and setter
     */
    public void setAccountBookName(String accountBookName) {
        this.accountBookName = accountBookName;
    }

    /** Not-null value. */
    /**
     * JavaDoc test getter and setter
     */
    public String getState() {
        return state;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    /**
     * JavaDoc test getter and setter
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * JavaDoc test getter
     */
    public int getIsDefault() {
        return isDefault;
    }

    /**
     * JavaDoc test getter
     */
    public void setIsDefault(int isDefault) {
        this.isDefault = isDefault;
    }

    /** Not-null value. */
    public java.util.Date getCreateDate() {
        return createDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreateDate(java.util.Date createDate) {
        this.createDate = createDate;
    }

}
