package com.example.aa.aaapp.greendao.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.aa.aaapp.greendao.model.AccountBookEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ACCOUNT_BOOK_ENTITY".
*/
public class AccountBookEntityDao extends AbstractDao<AccountBookEntity, Long> {

    public static final String TABLENAME = "ACCOUNT_BOOK_ENTITY";

    /**
     * Properties of entity AccountBookEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property AccountBookId = new Property(1, Integer.class, "accountBookId", false, "ACCOUNT_BOOK_ID");
        public final static Property State = new Property(2, String.class, "state", false, "STATE");
        public final static Property IsDefault = new Property(3, int.class, "isDefault", false, "IS_DEFAULT");
        public final static Property CreateDate = new Property(4, java.util.Date.class, "createDate", false, "CREATE_DATE");
    };


    public AccountBookEntityDao(DaoConfig config) {
        super(config);
    }
    
    public AccountBookEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ACCOUNT_BOOK_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"ACCOUNT_BOOK_ID\" INTEGER," + // 1: accountBookId
                "\"STATE\" TEXT NOT NULL ," + // 2: state
                "\"IS_DEFAULT\" INTEGER NOT NULL ," + // 3: isDefault
                "\"CREATE_DATE\" INTEGER NOT NULL );"); // 4: createDate
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_ACCOUNT_BOOK_ENTITY_ACCOUNT_BOOK_ID ON ACCOUNT_BOOK_ENTITY" +
                " (\"ACCOUNT_BOOK_ID\");");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ACCOUNT_BOOK_ENTITY\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, AccountBookEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer accountBookId = entity.getAccountBookId();
        if (accountBookId != null) {
            stmt.bindLong(2, accountBookId);
        }
        stmt.bindString(3, entity.getState());
        stmt.bindLong(4, entity.getIsDefault());
        stmt.bindLong(5, entity.getCreateDate().getTime());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public AccountBookEntity readEntity(Cursor cursor, int offset) {
        AccountBookEntity entity = new AccountBookEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // accountBookId
            cursor.getString(offset + 2), // state
            cursor.getInt(offset + 3), // isDefault
            new java.util.Date(cursor.getLong(offset + 4)) // createDate
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, AccountBookEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setAccountBookId(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setState(cursor.getString(offset + 2));
        entity.setIsDefault(cursor.getInt(offset + 3));
        entity.setCreateDate(new java.util.Date(cursor.getLong(offset + 4)));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(AccountBookEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(AccountBookEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
