package com.example.aa.aaapp.greendao.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * This entity is used for categoryEntity.
 * (This JavaDoc is defined in the generator project.)
 */
// This is another test comment, you could also apply annotations like this
public class CategoryEntity {

    /**
     * JavaDoc test field
     */
    private Long id;
    private Integer categoryId;
    /** Not-null value. */
    private String categoryName;
    private int typeFlag;
    private int parentId;
    /** Not-null value. */
    private String path;
    private int state;
    /** Not-null value. */
    private java.util.Date createDate;

    public CategoryEntity() {
    }

    public CategoryEntity(Long id) {
        this.id = id;
    }

    public CategoryEntity(Long id, Integer categoryId, String categoryName, int typeFlag, int parentId, String path, int state, java.util.Date createDate) {
        this.id = id;
        this.categoryId = categoryId;
        this.categoryName = categoryName;
        this.typeFlag = typeFlag;
        this.parentId = parentId;
        this.path = path;
        this.state = state;
        this.createDate = createDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getCategoryId() {
        return categoryId;
    }

    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /** Not-null value. */
    /**
     * JavaDoc test getter and setter
     */
    public String getCategoryName() {
        return categoryName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    /**
     * JavaDoc test getter and setter
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    /**
     * JavaDoc test getter
     */
    public int getTypeFlag() {
        return typeFlag;
    }

    /**
     * JavaDoc test getter
     */
    public void setTypeFlag(int typeFlag) {
        this.typeFlag = typeFlag;
    }

    /**
     * JavaDoc test getter
     */
    public int getParentId() {
        return parentId;
    }

    /**
     * JavaDoc test getter
     */
    public void setParentId(int parentId) {
        this.parentId = parentId;
    }

    /** Not-null value. */
    /**
     * JavaDoc test getter
     */
    public String getPath() {
        return path;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    /**
     * JavaDoc test getter
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * JavaDoc test getter
     */
    public int getState() {
        return state;
    }

    /**
     * JavaDoc test getter
     */
    public void setState(int state) {
        this.state = state;
    }

    /** Not-null value. */
    public java.util.Date getCreateDate() {
        return createDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreateDate(java.util.Date createDate) {
        this.createDate = createDate;
    }

}
