package com.example.aa.aaapp.greendao.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * This entity is used for payoutEntity.
 * (This JavaDoc is defined in the generator project.)
 */
// This is another test comment, you could also apply annotations like this
public class PayoutEntity {

    private Integer payoutId;
    private int accountBookId;
    /** Not-null value. */
    private String accountBookName;
    private int categoryId;
    /** Not-null value. */
    private String categoryName;
    /** Not-null value. */
    private String path;
    private int payWayId;
    private int placeId;
    private long amount;
    /** Not-null value. */
    private java.util.Date payoutDate;
    /** Not-null value. */
    private String payoutType;
    private int payoutUserId;
    /** Not-null value. */
    private String comment;
    /** Not-null value. */
    private java.util.Date createDate;
    private int state;

    public PayoutEntity() {
    }

    public PayoutEntity(Integer payoutId, int accountBookId, String accountBookName, int categoryId, String categoryName, String path, int payWayId, int placeId, long amount, java.util.Date payoutDate, String payoutType, int payoutUserId, String comment, java.util.Date createDate, int state) {
        this.payoutId = payoutId;
        this.accountBookId = accountBookId;
        this.accountBookName = accountBookName;
        this.categoryId = categoryId;
        this.categoryName = categoryName;
        this.path = path;
        this.payWayId = payWayId;
        this.placeId = placeId;
        this.amount = amount;
        this.payoutDate = payoutDate;
        this.payoutType = payoutType;
        this.payoutUserId = payoutUserId;
        this.comment = comment;
        this.createDate = createDate;
        this.state = state;
    }

    public Integer getPayoutId() {
        return payoutId;
    }

    public void setPayoutId(Integer payoutId) {
        this.payoutId = payoutId;
    }

    public int getAccountBookId() {
        return accountBookId;
    }

    public void setAccountBookId(int accountBookId) {
        this.accountBookId = accountBookId;
    }

    /** Not-null value. */
    public String getAccountBookName() {
        return accountBookName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAccountBookName(String accountBookName) {
        this.accountBookName = accountBookName;
    }

    public int getCategoryId() {
        return categoryId;
    }

    public void setCategoryId(int categoryId) {
        this.categoryId = categoryId;
    }

    /** Not-null value. */
    /**
     * JavaDoc test getter and setter
     */
    public String getCategoryName() {
        return categoryName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    /**
     * JavaDoc test getter and setter
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    /** Not-null value. */
    public String getPath() {
        return path;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPath(String path) {
        this.path = path;
    }

    public int getPayWayId() {
        return payWayId;
    }

    public void setPayWayId(int payWayId) {
        this.payWayId = payWayId;
    }

    public int getPlaceId() {
        return placeId;
    }

    public void setPlaceId(int placeId) {
        this.placeId = placeId;
    }

    public long getAmount() {
        return amount;
    }

    public void setAmount(long amount) {
        this.amount = amount;
    }

    /** Not-null value. */
    public java.util.Date getPayoutDate() {
        return payoutDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPayoutDate(java.util.Date payoutDate) {
        this.payoutDate = payoutDate;
    }

    /** Not-null value. */
    public String getPayoutType() {
        return payoutType;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPayoutType(String payoutType) {
        this.payoutType = payoutType;
    }

    public int getPayoutUserId() {
        return payoutUserId;
    }

    public void setPayoutUserId(int payoutUserId) {
        this.payoutUserId = payoutUserId;
    }

    /** Not-null value. */
    public String getComment() {
        return comment;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /** Not-null value. */
    public java.util.Date getCreateDate() {
        return createDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreateDate(java.util.Date createDate) {
        this.createDate = createDate;
    }

    public int getState() {
        return state;
    }

    public void setState(int state) {
        this.state = state;
    }

}
