package com.example.aa.aaapp.greendao.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * This entity is used by internal tests of greenDAO.
 * (This JavaDoc is defined in the generator project.)
 */
// This is another test comment, you could also apply annotations like this
public class UserEntity {

    private Long userId;
    /** Not-null value. */
    private String userStatus;
    /** Not-null value. */
    private String userName;
    /** Not-null value. */
    private java.util.Date createDate;

    public UserEntity() {
    }

    public UserEntity(Long userId) {
        this.userId = userId;
    }

    public UserEntity(Long userId, String userStatus, String userName, java.util.Date createDate) {
        this.userId = userId;
        this.userStatus = userStatus;
        this.userName = userName;
        this.createDate = createDate;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /** Not-null value. */
    /**
     * JavaDoc test getter and setter
     */
    public String getUserStatus() {
        return userStatus;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    /**
     * JavaDoc test getter and setter
     */
    public void setUserStatus(String userStatus) {
        this.userStatus = userStatus;
    }

    /** Not-null value. */
    /**
     * JavaDoc test getter
     */
    public String getUserName() {
        return userName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    /**
     * JavaDoc test getter
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /** Not-null value. */
    public java.util.Date getCreateDate() {
        return createDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreateDate(java.util.Date createDate) {
        this.createDate = createDate;
    }

}
