package com.example.aa.aaapp.greendao.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * This entity is used by internal tests of greenDAO.
 * (This JavaDoc is defined in the generator project.)
 */
// This is another test comment, you could also apply annotations like this
public class UserEntity {

    /**
     * JavaDoc test field
     */
    private Long id;
    private Integer userId;
    /** Not-null value. */
    private String userStatus;
    private int userName;
    /** Not-null value. */
    private java.util.Date createDate;

    public UserEntity() {
    }

    public UserEntity(Long id) {
        this.id = id;
    }

    public UserEntity(Long id, Integer userId, String userStatus, int userName, java.util.Date createDate) {
        this.id = id;
        this.userId = userId;
        this.userStatus = userStatus;
        this.userName = userName;
        this.createDate = createDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /** Not-null value. */
    /**
     * JavaDoc test getter and setter
     */
    public String getUserStatus() {
        return userStatus;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    /**
     * JavaDoc test getter and setter
     */
    public void setUserStatus(String userStatus) {
        this.userStatus = userStatus;
    }

    /**
     * JavaDoc test getter
     */
    public int getUserName() {
        return userName;
    }

    /**
     * JavaDoc test getter
     */
    public void setUserName(int userName) {
        this.userName = userName;
    }

    /** Not-null value. */
    public java.util.Date getCreateDate() {
        return createDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreateDate(java.util.Date createDate) {
        this.createDate = createDate;
    }

}
